version: '3'

services:
  web:
    restart: always
    build: .
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
    links:
      - db
      - dbtest
    env_file:
      - 'docker.env'
    command: >
      gunicorn -b 0.0.0.0:5000
      --workers=4
      --access-logfile -
      "app:create_app()"
      --reload
      -p pidfile

  db:
    restart: always
    image: 'postgres:12.2'
    env_file:
      - 'docker.env'
    volumes:
      - 'db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  dbtest:
    restart: always
    image: 'postgres:12.2'
    volumes:
      - 'dbtest:/var/lib/postgresql/test'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=teste
      - POSTGRES_USER=teste
      - POSTGRES_DB=bexsteste

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    links:
      - db

volumes:
  db:
  dbtest: